create extension if not exists pgcrypto;
create table users(uid text primary key,username text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),deleted_at timestamptz);
create table topics(id uuid primary key default gen_random_uuid(),slug text unique not null,label text unique not null,active boolean not null default true);
create table questions(id uuid primary key default gen_random_uuid(),author_uid text not null references users(uid),title text not null check(char_length(title) between 12 and 140),context text not null default '' check(char_length(context)<=2000),topic_id uuid not null references topics(id),language text not null default 'en',status text not null default 'open' check(status in('open','resolved','closed')),moderation_status text not null default 'visible' check(moderation_status in('pending','visible','hidden','removed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),edited_at timestamptz,accepted_answer_id uuid,deleted_at timestamptz);
create table answers(id uuid primary key default gen_random_uuid(),question_id uuid not null references questions(id),author_uid text not null references users(uid),body text not null check(char_length(body) between 20 and 5000),moderation_status text not null default 'visible',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),edited_at timestamptz,deleted_at timestamptz);
alter table questions add constraint accepted_answer_fk foreign key(accepted_answer_id) references answers(id);
create table helpful_votes(answer_id uuid not null references answers(id) on delete cascade,user_uid text not null references users(uid),created_at timestamptz not null default now(),primary key(answer_id,user_uid));
create table follows(question_id uuid not null references questions(id) on delete cascade,user_uid text not null references users(uid),created_at timestamptz not null default now(),primary key(question_id,user_uid));
create table saves(question_id uuid not null references questions(id) on delete cascade,user_uid text not null references users(uid),created_at timestamptz not null default now(),primary key(question_id,user_uid));
create table activity(id uuid primary key default gen_random_uuid(),recipient_uid text not null references users(uid),kind text not null,question_id uuid references questions(id),answer_id uuid references answers(id),created_at timestamptz not null default now(),read_at timestamptz);
create table blocks(blocker_uid text not null references users(uid),blocked_uid text not null references users(uid),created_at timestamptz not null default now(),primary key(blocker_uid,blocked_uid),check(blocker_uid<>blocked_uid));
create table reports(id uuid primary key default gen_random_uuid(),reporter_uid text not null references users(uid),target_type text not null check(target_type in('question','answer','user')),target_id text not null,reason text not null,status text not null default 'open',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index one_open_report_per_target on reports(reporter_uid,target_type,target_id) where status='open';
create table moderation_actions(id uuid primary key default gen_random_uuid(),report_id uuid not null references reports(id),decision text not null check(decision in('dismiss','hide','remove')),note text not null default '' check(char_length(note)<=500),created_at timestamptz not null default now());
create index questions_feed on questions(moderation_status,status,created_at desc) where deleted_at is null;
create index answers_thread on answers(question_id,created_at) where deleted_at is null;
create index activity_unread on activity(recipient_uid,created_at desc) where read_at is null;
insert into topics(slug,label) values('technology','Technology'),('work-business','Work and business'),('education','Education'),('daily-life','Daily life'),('health-wellbeing','Health and wellbeing'),('money-basics','Money basics'),('relationships','Relationships'),('pi-ecosystem','Pi ecosystem'),('other','Other') on conflict do nothing;
create or replace function delete_questora_account(target_uid text) returns void language plpgsql security definer set search_path=public as $$
begin
  update questions set moderation_status='removed',deleted_at=now(),updated_at=now() where author_uid=target_uid and deleted_at is null;
  update answers set moderation_status='removed',deleted_at=now(),updated_at=now() where author_uid=target_uid and deleted_at is null;
  delete from helpful_votes where user_uid=target_uid;
  delete from follows where user_uid=target_uid;
  delete from saves where user_uid=target_uid;
  delete from blocks where blocker_uid=target_uid or blocked_uid=target_uid;
  update users set username='Deleted Pioneer',deleted_at=now(),updated_at=now() where uid=target_uid;
end;
$$;
revoke all on function delete_questora_account(text) from public, anon, authenticated;
grant execute on function delete_questora_account(text) to service_role;
